import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { NavBar } from "@/components/navbar/navbar";
import { Sidebar } from "@/components/sidebar/sidebar";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`${inter.className} flex items-start justify-between`}>
        <Sidebar />
        <main className="grid h-full w-full pl-[300px]">
          <NavBar />
          <div className="p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
